#!/bin/bash

git add     public/images/bg-textbox.gif
git add     public/images/bg-toplevel-hover.gif
git add     public/images/bg-toplevel-hover.png
git add     public/images/bg-toplevel.gif
git add     public/images/bg-topnav-mask.gif
git add     public/images/bg_tableRow.gif
git add     public/images/bt-login.gif
git add     public/images/bt-send-form.gif
git add     public/images/error.png
git add     public/images/icon-blue-arrow.gif
git add     public/images/icon-calendar.gif
git add     public/images/icon-confirm.gif
git add     public/images/icon-delete-message.gif
git add     public/images/icon-delete.gif
git add     public/images/icon-edit.gif
git add     public/images/icon-error.gif
git add     public/images/icon-greet-user.gif
git add     public/images/icon-messages.gif
git add     public/images/icon-quick-send-message.gif
git add     public/images/input-required.png
git add     public/images/link-arrow-hover.gif
git add     public/images/link-arrow-regular.gif
git add     public/images/notice.png
git add     public/images/ql-databases.gif
git add     public/images/ql-design.gif
git add     public/images/ql-media.gif
git add     public/images/ql-messages.gif
git add     public/images/ql-options.gif
git add     public/images/ql-paths.gif
git add     public/images/ql-photos.gif
git add     public/images/ql-settings.gif
git add     public/images/ql-users.gif
git add     public/images/submenuhover.gif
git add     public/images/success.png
git add     public/images/sunny.png
git add     public/system/images/4/
